// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB07eQfa5TOxrh8PSWWKNyZ9XQ2gBIij-U',
    appId: '1:1024788827328:web:0518993811244f60277125',
    messagingSenderId: '1024788827328',
    projectId: 'isearch-a8d14',
    authDomain: 'isearch-a8d14.firebaseapp.com',
    storageBucket: 'isearch-a8d14.firebasestorage.app',
    measurementId: 'G-2DP5BPDBR1',
  );


    
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5uVrtaQc-Vy2v0tdJWA9lc9YkZgmZBQ',
    appId: '1:1024788827328:android:1343c841dbd92c5b277125',
    messagingSenderId: '1024788827328',
    projectId: 'isearch-a8d14',
    storageBucket: 'isearch-a8d14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCFMgf7nZo-4sADQ6xu6jw6t7IqIzULg',
    appId: '1:1024788827328:ios:ba41ed5e61f5744a277125',
    messagingSenderId: '1024788827328',
    projectId: 'isearch-a8d14',
    storageBucket: 'isearch-a8d14.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZCFMgf7nZo-4sADQ6xu6jw6t7IqIzULg',
    appId: '1:1024788827328:ios:ba41ed5e61f5744a277125',
    messagingSenderId: '1024788827328',
    projectId: 'isearch-a8d14',
    storageBucket: 'isearch-a8d14.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB07eQfa5TOxrh8PSWWKNyZ9XQ2gBIij-U',
    appId: '1:1024788827328:web:0945b4184e398b3e277125',
    messagingSenderId: '1024788827328',
    projectId: 'isearch-a8d14',
    authDomain: 'isearch-a8d14.firebaseapp.com',
    storageBucket: 'isearch-a8d14.firebasestorage.app',
    measurementId: 'G-Q35KEVBZCY',
  );

}
